# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '7c98ad99-f45d-45f4-b613-98c0edaca2b0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/GetItDone4/AzureRmPipeline4/main/CreateWebApp/azuredeploy.json?token=GHSAT0AAAAAABRVGDKJVSJLVOUA3ZDIUZSOYSZORKQ'
    overrideParameters: '-projectName [EnterAProjectName]'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'